### ISSUE TITLE
ReferenceError: getReactVersion is not defined

### ISSUE THREAD

**Issue by jbertrand-siliconsalad** [rnpm/rnpm-plugin-link#32]
I try to unlink react-native-camer, but I get this error : 
```
$ rnpm unlink react-native-camera
rnpm info Unlinking react-native-camera android dependency
/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/android/unregisterNativeModule.js:11
  const prefix = getPrefix(getReactVersion(projectConfig.folder));
                           ^

ReferenceError: getReactVersion is not defined
    at unregisterNativeAndroidModule (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/android/unregisterNativeModule.js:11:28)
    at Object.unlink [as func] (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/unlink.js:42:30)
    at Command.runAction (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/bin/cli:24:15)
    at Command.listener (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:100:13)
    at Command.emit (events.js:185:7)
    at Command.parseArgs (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/commander/index.js:615:12)
    at Command.parse (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/bin/cli:30:5)
    at Module._compile (module.js:413:34)
```

I tried to add `const getReactVersion = require('../getReactNativeVersion');` at line 6 of `rnpm-plugin-link/src/android/unregisterNativeModule.js` and I get this error : 
```
$ rnpm unlink react-native-camera
rnpm info Unlinking react-native-camera android dependency
module.js:341
    throw err;
    ^

Error: Cannot find module './patches/0.18/addPackagePath'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at unregisterNativeAndroidModule (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/android/unregisterNativeModule.js:32:30)
    at Object.unlink [as func] (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/unlink.js:42:30)
    at Command.runAction (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/bin/cli:24:15)
    at Command.listener (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:100:13)
    at Command.emit (events.js:185:7)
```

After some research I found that there is a file called `addPackagePatch` (and NOT addPackagePath) so I tried to change the name but I get this error : 
```
$ rnpm unlink react-native-camera
rnpm info Unlinking react-native-camera android dependency
/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/android/patches/0.18/addPackagePatch.js:2
  ',\n        ' + config.packageInstance;
                        ^

TypeError: Cannot read property 'packageInstance' of undefined
    at module.exports (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/android/patches/0.18/addPackagePatch.js:2:25)
    at /Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/android/unregisterNativeModule.js:67:35
    at /Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/lodash.flowright/index.js:38:31
    at unregisterNativeAndroidModule (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/android/unregisterNativeModule.js:71:8)
    at Object.unlink [as func] (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/unlink.js:42:30)
    at Command.runAction (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/bin/cli:24:15)
    at Command.listener (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:100:13)
    at Command.emit (events.js:185:7)
    at Command.parseArgs (/Users/jbertrand/.nvm/versions/node/v5.6.0/lib/node_modules/rnpm/node_modules/commander/index.js:615:12)
```

And I'm stuck here :disappointed:

**Comment by grabbou** [comment]
@Kureev?

**Comment by Kureev** [comment]
Oops, will fix it asap

**Comment by grabbou** [comment]
How come the tests are passing that?

**Comment by Kureev** [comment]
no clue, going to investigate it

**Comment by grabbou** [comment]
Thanks!
