### ISSUE TITLE
[iOS] Cannot read property 'replace' of undefined at getPlistPath

### ISSUE THREAD

**Issue by rclai** [rnpm/rnpm-plugin-link#35]
RN 0.20.0
RNPM 1.4.1

This is when I tried linking `react-native-vector-icons`.

```jsx
/Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/getPlistPath.js:8
    .replace(/"/g, '')
    ^

TypeError: Cannot read property 'replace' of undefined
    at getPlistPath (/Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/getPlistPath.js:8:5)
    at linkAssetsIOS (/Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/copyAssets.js:17:56)
    at /Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/link.js:63:5
    at /Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/node_modules/async/lib/async.js:718:13
    at iterate (/Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/node_modules/async/lib/async.js:262:13)
    at /Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/node_modules/async/lib/async.js:274:29
    at /Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/node_modules/async/lib/async.js:44:16
    at /Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/node_modules/async/lib/async.js:723:17
    at /Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/node_modules/async/lib/async.js:167:37
    at /Users/richardlai/.nvm/versions/node/v4.3.1/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/node_modules/async/lib/async.js:52:16
```

My file dir is:
```
- root
  - node_modules
  - ios
    - Pods
    - Podfile
    - project.xcodeproj
    - project.xcworkspace
    - Podfile
    - existingiOSApp
      - myapp.plist
```

**Comment by grabbou** [comment]
Is your plist named `myapp`, not `Info.plist`? Didn't know that was possible.

**Comment by rclai** [comment]
Yes it is apparently.

**Comment by grabbou** [comment]
I am submitting a temporary fix to not break in such case. Do you have INFOPLIST_FILE value set in your .pbxproj?

**Comment by grabbou** [comment]
Ok, this has been properly identified. Closing in favor of https://github.com/rnpm/rnpm/issues/114 that has steps to reproduce! Thanks!

**Comment by rclai** [comment]
Cool thanks man!
