### ISSUE TITLE
searchPaths.filter is not a function

### ISSUE THREAD

**Issue by 999946** [rnpm/rnpm-plugin-link#94]
```
rnpm unlink react-native-image-picker
rnpm-link info Android module react-native-image-picker is not installed 
rnpm-link info Unlinking react-native-image-picker ios dependency 
/usr/local/Cellar/nvm/0.31.0/versions/node/v6.2.0/lib/node_modules/rnpm/node_modules/xcode/lib/pbxProject.js:1147
            var matches = searchPaths.filter(function(p) {
                                      ^

TypeError: searchPaths.filter is not a function
    at pbxProject.removeFromLibrarySearchPaths (/usr/local/Cellar/nvm/0.31.0/versions/node/v6.2.0/lib/node_modules/rnpm/node_modules/xcode/lib/pbxProject.js:1147:39)
    at removeFromStaticLibraries (/usr/local/Cellar/nvm/0.31.0/versions/node/v6.2.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/removeFromStaticLibraries.js:17:11)
    at getProducts.forEach.product (/usr/local/Cellar/nvm/0.31.0/versions/node/v6.2.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/unregisterNativeModule.js:36:5)
    at Array.forEach (native)
    at unregisterNativeModule (/usr/local/Cellar/nvm/0.31.0/versions/node/v6.2.0/lib/node_modules/rnpm/node_modules/rnpm-plugin-link/src/ios/unregisterNativeModule.js:35:34)
```
RN v0.28
nvm v0.31.0
node v6.2.0

**Comment by tomazahlin** [comment]
I have the same problem!! Any help?? But I think this is react-native-image-picker related, maybe it is better to ask there.

**Comment by Kureev** [comment]
cc @grabbou

**Comment by jjhesk** [comment]
@grabbou i got this issue also. please help us..

**Comment by Amurmurmur** [comment]
Same issue here

**Comment by Jarred-Sumner** [comment]
same issue

**Comment by grabbou** [comment]
Please use react-native link instead of `rnpm link`. This plugin is no
longer maintained as it's been merged into react-native core and that's the
place where we accept contributions to it.

**Comment by fdnhkj** [comment]
I have the same issue when unlinking react-native-svg iOS dependency with `react-native` CLI.

> hakaj$ react-native unlink react-native-svg
> Scanning 621 folders for symlinks in /Users/hakaj/code-projects/my-proximus-app/node_modules (16ms)
> rnpm-install info Android module react-native-svg is not installed
> rnpm-install info Unlinking react-native-svg ios dependency
> rnpm-install ERR! It seems something went wrong while unlinking. Error: searchPaths.filter is not a function

**Comment by hbarylskyi** [comment]
solution can be found [here](https://github.com/facebook/react-native/issues/13160#issuecomment-291054688)
